# Generated by Django 4.2.11 on 2024-03-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='gallery_post',
        ),
    ]
