# Generated by Django 4.2.11 on 2024-03-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_gallery_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='images/job_gallery/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(upload_to='images/company_logos/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='profile_image',
            field=models.ImageField(upload_to='images/job_profile_images/'),
        ),
    ]
