# Generated by Django 4.2.11 on 2024-03-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_galleryimage_image_alter_job_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='static/images/job_gallery/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(upload_to='static/images/company_logos/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='profile_image',
            field=models.ImageField(upload_to='static/images/job_profile_images/'),
        ),
    ]
