# Generated by Django 5.0.6 on 2024-06-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_jobvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="referral_code",
            field=models.CharField(default="", max_length=50),
        ),
    ]
