# Generated by Django 4.2.11 on 2024-04-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_email_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
