# Generated by Django 4.2.11 on 2024-05-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_forgot_password',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
