# Generated by Django 4.2.11 on 2024-06-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_last_forgot_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
